# Generated by Django 2.2.12 on 2024-03-31 17:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autor_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['autor_id'],
            },
        ),
        migrations.CreateModel(
            name='FahrplanZug',
            fields=[
                ('path', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gattung', models.CharField(max_length=20)),
                ('nummer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None)),
                ('is_reisezug', models.BooleanField(verbose_name='Zugart')),
                ('zug_lauf', models.CharField(max_length=200, null=True, verbose_name='Lauf')),
                ('fahrplan_gruppe', models.CharField(max_length=200, null=True)),
                ('deko', models.BooleanField(default=False)),
                ('speed_anfang', models.IntegerField(null=True)),
                ('speed_zug', models.IntegerField(null=True)),
                ('bremsstellung', models.IntegerField(null=True)),
                ('fis_ansagen', models.BooleanField(default=False)),
                ('masse', models.IntegerField(null=True)),
                ('laenge', models.FloatField(null=True)),
                ('bremse_percentage', models.FloatField(null=True)),
                ('zeit_bewegung', models.DurationField(null=True)),
                ('fahrzeug_tree', django.contrib.postgres.fields.jsonb.JSONField()),
                ('bild', models.ImageField(max_length=200, null=True, upload_to='trn/')),
                ('autor', models.ManyToManyField(to='datenbank.Autor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fuehrerstand',
            fields=[
                ('path', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mit_afb', models.BooleanField(default=False)),
                ('zugsicherung', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('sifa', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('tuer_system', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('schleuderschutz', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None)),
                ('notbremse_system', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('autor', models.ManyToManyField(to='datenbank.Autor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreckenModule',
            fields=[
                ('path', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('standorte', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
                ('fehlende_nachbaren', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
                ('autor', models.ManyToManyField(to='datenbank.Autor')),
                ('nachbaren', models.ManyToManyField(related_name='_streckenmodule_nachbaren_+', to='datenbank.StreckenModule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FahrzeugVariante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_file', models.CharField(max_length=200)),
                ('haupt_id', models.IntegerField()),
                ('neben_id', models.IntegerField()),
                ('br', models.CharField(max_length=50, verbose_name='BR')),
                ('dekozug', models.BooleanField(verbose_name='Deko')),
                ('beschreibung', models.CharField(max_length=200, null=True)),
                ('farbgebung', models.CharField(max_length=200, null=True)),
                ('einsatz_ab', models.DateTimeField(null=True)),
                ('einsatz_bis', models.DateTimeField(null=True)),
                ('ls3_datei', models.CharField(max_length=200)),
                ('masse', models.FloatField(null=True)),
                ('laenge', models.FloatField()),
                ('speed_max', models.IntegerField()),
                ('bremse', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('tuersystem', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), null=True, size=None)),
                ('antrieb', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
                ('neigetechnik', models.BooleanField(default=False, verbose_name='Neige')),
                ('stromabnehmer_hoehe', models.FloatField(null=True)),
                ('bild_klein', models.ImageField(max_length=200, null=True, upload_to='fzg/')),
                ('autor', models.ManyToManyField(to='datenbank.Autor')),
                ('fuehrerstand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fahrzeuge', to='datenbank.Fuehrerstand')),
            ],
            options={
                'ordering': ['root_file', 'haupt_id', 'neben_id'],
            },
        ),
        migrations.CreateModel(
            name='FahrplanZugEintrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('an', models.DateTimeField(null=True)),
                ('ab', models.DateTimeField(null=True)),
                ('ort', models.CharField(max_length=200)),
                ('bedarfshalt', models.BooleanField(default=False)),
                ('kopf_machen', models.BooleanField(default=False)),
                ('ereignis', models.BooleanField(default=False)),
                ('zug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eintraege', to='datenbank.FahrplanZug')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='fahrplanzug',
            name='fahrzeuge',
            field=models.ManyToManyField(related_name='fahrplanzuege', to='datenbank.FahrzeugVariante'),
        ),
        migrations.AddField(
            model_name='fahrplanzug',
            name='steuerfahrzeug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steuerfahrplanzuege', to='datenbank.FahrzeugVariante'),
        ),
        migrations.AddField(
            model_name='fahrplanzug',
            name='triebfahrzeug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triebfahrplanzuege', to='datenbank.FahrzeugVariante'),
        ),
        migrations.CreateModel(
            name='Fahrplan',
            fields=[
                ('path', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('anfang', models.DateTimeField()),
                ('autor', models.ManyToManyField(to='datenbank.Autor')),
                ('strecken_modules', models.ManyToManyField(related_name='fahrplaene', to='datenbank.StreckenModule')),
                ('zuege', models.ManyToManyField(related_name='fahrplaene', to='datenbank.FahrplanZug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuehrerstandBlick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild_klein', models.ImageField(max_length=200, unique=True, upload_to='ftd/')),
                ('nummer', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('fuehrerstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blicke', to='datenbank.Fuehrerstand')),
            ],
            options={
                'ordering': ['nummer'],
                'unique_together': {('nummer', 'fuehrerstand')},
            },
        ),
    ]
